modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="donkeykongmod" #mandatory
version="1" #mandatory
displayName="Donkey Kong Mod" #mandatory
logoFile="examplemod.png" #optional
credits="A mod by LandoSpuk" #optional
authors="Landospuk" #optional
description='''
Bringing your favorite monkey into Minecraft!
'''
[[dependencies.donkeykongmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.donkeykongmod]]
    modId="Minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
