
[oregen]
	#Decide if you want maggot ores to spawn in the overworld
	generate_overworld = true
	#Maximum number of ore veins of the crystal ore that can spawn in one chunk.
	#Range: 8 ~ 20
	crystal_ore_chance = 10

